theme: jekyll-theme-minimal
title: Elias Castegren
description: Associate Senior Lecturer at <a href="https://www.uu.se/en/contact-and-organisation/staff?query=N12-2050">Uppsala University</a>
show_downloads: false
twitter_username: CartesianGlee